### ISSUE TITLE
/oauth2/callback endpoint implementation

### ISSUE THREAD

**Issue by Opalo** [bitly/oauth2_proxy#445]
Hi,

Do I have to provide my own implementation of `/oauth2/callback` endpoint or oauth2_proxy handles it for me? I've a nginx instance in front of oauth2_proxy (for HTTPS) and the following configuration file:

```
server {
  listen         80;
  server_name    example.com;
  return         301 https://$server_name$request_uri;
}

server {
  listen         443 ssl;
  server_name    example.com;

  ssl_certificate /etc/nginx/ssl/nginx.crt;
  ssl_certificate_key /etc/nginx/ssl/nginx.key;

  add_header Strict-Transport-Security max-age=2592000;

  location / {
    proxy_pass http://oauth2proxy:4180;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_connect_timeout 1;
    proxy_send_timeout 30;
    proxy_read_timeout 30;
  }

}
```
Everything works fine until `/oauth2/callback` request is issued - it results in 404. How to configure it properly? After successful authentication I need to redirect the request to `/some` endpoint. Here is my docker compose file, since it might be relevant as well.
```

version: '2'

services:

  nginx:
    image: nginx:1.13.5
    container_name: nginx
    volumes:
      - {{ nginx_dir }}/certs/:/etc/nginx/ssl/
      - {{ nginx_dir }}/config/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    networks:
      - main
    restart: always   

  oauth2proxy:
    image: schasse/oauth2_proxy
    container_name: oauth2proxy
    ports:
      - 4180:4180
    networks:
      - main
    command: --upstream="http://nginx:80" --http-address="0.0.0.0:4180" --cookie-secret={{ cookie_secret }} --client-id={{ client_id }} --client-secret={{ client_secret }} --email-domain="example.com"
    restart: always   
 
networks:
  main:
```
