### ISSUE TITLE
App segfaults on improper upstream address

### ISSUE THREAD

**Issue by mkaput** [bitly/oauth2_proxy#468]
oauth2-proxy v2.2 crashes with:

```
oauth2-proxy[3436]: panic: runtime error: invalid memory address or nil pointer dereference
oauth2-proxy[3436]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7ae03f]
oauth2-proxy[3436]: goroutine 1 [running]:
oauth2-proxy[3436]: main.(*Options).Validate(0xc4200e2000, 0xc4200e2000, 0xc4200104e0)
oauth2-proxy[3436]:         /Users/jehiah/projects/gopath/src/github.com/bitly/oauth2_proxy/options.go:149 +0x30f
oauth2-proxy[3436]: main.main()
oauth2-proxy[3436]:         /Users/jehiah/projects/gopath/src/github.com/bitly/oauth2_proxy/main.go:101 +0x1303
```

on such config (note missing `http://.../`):

```
upstreams = ["127.0.0.1:5601"]
```

**Comment by ploxiln** [comment]
fixed in #431 I believe

**Comment by mkaput** [comment]
👍

**Comment by adamdecaf** [comment]
FYI, I ran into this when adding quotes around the a kubernetes args option.

This was the **bad** config. 
```yaml
containers:
      - args:
        - ...
        - --upstream="http://prometheus.infrastructure.svc.cluster.local:9090/"
```

This was the **good** config. 
```yaml
containers:
      - args:
        - ...
        - --upstream=http://prometheus.infrastructure.svc.cluster.local:9090/
```
