### ISSUE TITLE
Using oauth2_proxy with nginx k8s ingress

### ISSUE THREAD

**Issue by nmiculinic** [bitly/oauth2_proxy#558]
kubernetes nginx controller supports external auth via:

https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/annotations.md#external-authentication

However, I'm not sure how can I use it since I'm a beginner regarding nginx and k8s nginx controller.

**Comment by bismarck** [comment]
There is an example in the ingress-nginx repository using external auth:

https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/external-auth

**Comment by ean** [comment]
To get deep linking to work I needed to add this patch, it is hacky as the nginx ingress does not encode the query pairs properly:

diff --git a/oauthproxy.go b/oauthproxy.go
index 21e5dfc..275a975 100644
--- a/oauthproxy.go
+++ b/oauthproxy.go
@@ -426,9 +426,27 @@ func (p *OAuthProxy) GetRedirect(req *http.Request) (redirect string, err error)
        }

        redirect = req.Form.Get("rd")
+       if req.URL.Query().Get("rd") != "" {
+               elements := strings.SplitN(req.URL.String(), "/start?rd=", 2)
+               if len(elements) == 2 {
+                       u, err := url.Parse(elements[1])
+                       if err == nil {
+                               redirect = u.Path
+                               if u.RawQuery != "" {
+                                       redirect += "?" + u.RawQuery
+                               }
+                               if u.Fragment != "" {
+                                       redirect += "#" + u.Fragment
+                               }
+                       } else {
+                               fmt.Printf("Parse failed: %s\n", req.URL.Query().Get("rd"))
+                       }
+               }
+       }
        if redirect == "" || !strings.HasPrefix(redirect, "/") || strings.HasPrefix(redirect, "//") {
                redirect = "/"
        }
+       fmt.Printf("Redirect is: %s\n", redirect)

        return
 }

**Comment by nmiculinic** [comment]
@ean 

What exactly nginx does, and what it should do? Do you have an example?

**Comment by ean** [comment]
The nginx ingress controller requests auth using this statement:
            error_page 401 = https://host/oauth2/start?rd=$scheme://$http_host$request_uri;
Where the $scheme://$http_host$request_uri should be url encoded, which would allow us to fetch the value using the standard request API in go instead of doing manual parsing of the url string.

**Comment by nmiculinic** [comment]
https://github.com/openresty/set-misc-nginx-module#set_escape_uri

Can we use something like this?

**Comment by nmiculinic** [comment]
Also I've tried your patched and it didn't help

**Comment by ean** [comment]
My ingress setup look like this:
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-signin: https://hostname.example.net/oauth2/start
    ingress.kubernetes.io/auth-url: https://hostname.example.net/oauth2/auth
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels:
    app: foo
  name: foo
spec:
  rules:
  - host: hostname.example.net
    http:
      paths:
      - path: /
        backend:
          serviceName: foo
          servicePort: 3000
  tls:
  - hosts:
    - hostname.example.net
    secretName: foo-tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels:
    app: foo
  name: foo-auth
spec:
  rules:
  - host: hostname.example.net
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: auth-proxy-v1
          servicePort: 4180
  tls:
  - hosts:
    - hostname.example.net
    secretName: foo-tls
```

where auto-proxy-v1 is a service that exposes the oauth2-proxy instance. I will look at what is needed to get redirect to work if the oauth2-proxy is exposed on a separate external hostname to avoid having two ingresses for all exposed services. But that requires some more changes to the oauth2-proxy code it seems.
